spring:
  application:
    name: curriculums-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curriculums
    username: pippo
    password: pluto
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          utenti-service:
            url: http://localhost:8070/app/v1/utenti


server:
  port: 8073

application:
  config:
    utenti-url: http://localhost:8070/app/v1/utenti
    posizioniLavorative-url: http://localhost:8070/app/v1/posizioneLavorativa
    comunicazione-aziendale-url: http://localhost:8071/app/v1/comunicazioneAziendale
    news-url: http://localhost:8071/app/v1/news

file:
  upload-dir-curriculum: ./services/curriculums/src/main/java/com/appAziendaleMicroservizi/curriculums/files/curriculum