spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/utenti
    username: pippo
    password: pluto
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: localhost # Se l’app gira in locale e MailDev è su Docker Desktop in ascolto su localhost
    port: 1025 # Porta SMTP di MailDev
    username: # Vuoto se non serve autenticazione
    password: # Vuoto se non serve autenticazione
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

application:
  config:
    comunicazione-aziendale-url: http://localhost:8071/app/v1/comunicazioneAziendale
    curriculum-url: http://localhost:8073/app/v1/curriculums
    token-blackList-url: http://localhost:8222/app/v1/tokenBlackList