spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false  # Disabilita la protezione di auto-preservazione per facilitare i test
  client:
    register-with-eureka: false  # Non è necessario per il server Eureka
    fetch-registry: false        # Non è necessario per il server Eureka
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/  # URL dove il server Eureka è in ascolto

server:
  port: 8761  # La porta del server Eureka
