spring:
  application:
    name: pubblicazioni-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pubblicazioni #utenti, posizione lavorativa e dipartimento
    username: pippo
    password: pluto
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          utenti-service:
            url: http://localhost:8070/app/v1/utenti

  kafka:
    producer:
      bootstrap-server: localhost:9092
      group-id: pubblicazioni-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: pubblicazioneConfirmation:com.appAziendaleMicroservizi.pubblicazioni.kafka.PubblicazioneConfirmation


server:
  port: 8071

application:
  config:
    utenti-url: http://localhost:8070/app/v1/utenti
    posizioniLavorative-url: http://localhost:8070/app/v1/posizioneLavorativa
    comunicazione-aziendale-url: http://localhost:8071/app/v1/comunicazioneAziendale