spring:
  application:
    name: utente-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/utenti #utenti, posizione lavorativa e dipartimento
    username: pippo
    password: pluto
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: "GbOGC6XP6uhqfNUzDIYeqqwO34Ne1EuMOrtsiatc0wo="

application:
  config:
    comunicazione-aziendale-url: http://comunicazione-aziendale-service/app/v1/comunicazioneAziendale
    curriculum-url: http://curriculum-service/app/v1/curriculums
    token-blackList-url: http://localhost:8222/app/v1/tokenBlackList
