spring:
  application:
    name: utente-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/utenti #utenti, posizione lavorativa e dipartimento
    username: pippo
    password: pluto
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8070

application:
  config:
    utenti-url: http://localhost:8070/app/v1/utenti
    comunicazione-aziendale-url: http://localhost:8071/app/v1/comunicazioneAziendale