spring:
  application:
    name: timbri-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/timbri
    username: pippo
    password: pluto
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: mail_appAziendale # Nome del container Docker
    port: 1025      # Porta SMTP di MailDev
    username: ""    # MailDev non richiede autenticazione
    password: ""    # MailDev non richiede autenticazione
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8072

application:
  config:
    utenti-url: http://localhost:8070/app/v1/utenti
    comunicazione-aziendale-url: http://localhost:8071/app/v1/comunicazioneAziendale

file:
  upload-daily-dir-timbri: ./services/timbri/src/main/java/com/appAziendaleMicroservizi/timbri/files/timbriGiornalieri