server:
  port: 8222  # Porta del Gateway

spring:
  config:
    import: optional:configserver:http://localhost:8888  # Configurazione esterna se usi un config server
  application:
    name: gateway-service  # Nome del tuo Gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true  # Abilita la discovery locator
            lower-case-service-id: true  # Converti gli id dei servizi in minuscolo
        routes:
          - id: utente-route
            uri: lb://utente-service # Usa Eureka per risolvere l'URL
            predicates:
              - Path=/app/v1/utenti/**


          - id: dipartimento-route
            uri: lb://utente-service  # Usa Eureka per risolvere l'URL
            predicates:
              - Path=/app/v1/dipartimento/**


          - id: posizioneLavorativa-route
            uri: lb://utente-service # Usa Eureka per risolvere l'URL
            predicates:
              - Path=/app/v1/posizioneLavorativa/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Assicurati che questa URL sia corretta
    register-with-eureka: false   # Se non vuoi che il Gateway si registri su Eureka
    fetch-registry: true         # Abilita il recupero del registro da Eureka


